constellation_card_word_categories = [{"word": "la",
                                       "groups": ["FÉMININE", "GÉOMÉTRIE"],
                                       "notes": ["singular, also a homonym for “there” (là) in French, so "]},
                                      {"word": "naissance",
                                       "groups": ["GENÈSES"]},
                                      {"word": "et",
                                       "groups": ["MATHÉMATIQUES", "CONJONCTION"]},
                                      {"word": "la",
                                       "notes": ["See above"]},
                                      {"word": "mort",
                                       "groups": ["GENÈSES"]},
                                      {"word": "comme",
                                       "groups": ["ONTOLOGIE", "RELATION"]},
                                      {"word": "moments",
                                       "groups": ["PHYSIQUE", "ESPACE_TEMPS"]},
                                      {"word": "ponctuels",
                                       "groups": ["GÉOMÉTRIE", "PHYSIQUE"],
                                       "notes": ["Zero-dimensional space-time.",
                                                 "points on a map",
                                                 "points of time"]},
                                      {"word": "et",
                                       "notes": ["See above"]},
                                      {"word": "intervalle",
                                       "groups": ["GÉOMÉTRIE"],
                                       "notes": ["One-dimensional space"]},
                                      {"word": "qui",
                                       "groups": ["ONTOLOGIE"]},
                                      {"word": "les",
                                       "groups": ["MATHÉMATIQUES"]},
                                      {"word": "separe",
                                       "groups": ["GÉOMÉTRIE"]},
                                      {"word": "se",
                                       "groups": ["ONTOLOGIE"],
                                       "notes": [
                                           "reflexive verbs have their own logic related to the reflexivity of the reduction, to the asymmetry that occurs because one can never see oneself from the outside: The Self can only see the Other. Only the Other can see the Self. The Self can never view the Self from the inside. The Self can only view the Self as an Other"]},
                                      {"word": "logent",
                                       "groups": ["PHYSIQUE",
                                                  "GENÈSES"],
                                       "notes": [
                                           "both space intervals, time intervals, geodesic neigborhoods, as well as a home for the family"]},
                                      {"word": "dans",
                                       "groups": [
                                           "GÉOMÉTRIE",
                                           "DANS"]},
                                      {"word": "ce",
                                       "groups": [
                                           "MATHÉMATIQUES"]},
                                      {"word": "temps",
                                       "groups": ["PHYSIQUE"]},
                                      {"word": "universel",
                                       "groups": ["ONTOLOGIE", "MATHÉMATIQUES"]},
                                      {"word": "de",
                                       "groups": ["ONTOLOGIE", "GENÈSES"]},
                                      {"word": "historien"
                                       },
                                      {"word": "qui",
                                       "groups": ["ONTOLOGIE"]},
                                      {"word": "est",
                                       "groups": ["ONTOLOGIE"]},
                                      {"word": "un",
                                       "groups": ["ONTOLOGIE", "MATHÉMATIQUES"]},
                                      {"word": "survivan",
                                       "groups": ["MATHÉMATIQUES", "GENÈSES", "GÉOMÉTRIE"],
                                       "notes": [
                                           "The survivor is the one who lives on top of the one who died, who lives out the Beyond of the one who he has murdered, the father of the past"]
                                       }
                                      ]
