from django.db import migrations, models

ID_FIELD = ('id', models.AutoField(auto_created=True,
                                   primary_key=True,
                                   serialize=True,
                                   verbose_name='ID'))

FRENCH_WORD_COL = ('french', models.CharField(max_length=100, null=True, unique=True))
ENGLISH_WORD_COL = ('english', models.CharField(max_length=100, null=True, unique=True))
FRENCH_EXPLANATION_COL = ('french_explanation', models.TextField(null=True))
ENGLISH_EXPLANATION_COL = ('english_explanation', models.TextField(null=True))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(name='Etymology',
                               fields=[ID_FIELD,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL]),
        migrations.CreateModel(name='Definition',
                               fields=[ID_FIELD,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL]),
        migrations.CreateModel(name='SemanticCategory',
                               fields=[ID_FIELD,
                                       FRENCH_WORD_COL,
                                       ENGLISH_WORD_COL,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL]),
        migrations.CreateModel(name='EtymologicalRoot',
                               fields=[ID_FIELD,
                                       ('root', models.CharField(max_length=100, null=True, unique=True)),
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL
                                       ]),
        migrations.CreateModel(name='VerbType',
                               fields=[ID_FIELD,
                                       FRENCH_WORD_COL,
                                       ENGLISH_WORD_COL,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL]),
        migrations.CreateModel(name='NounType',
                               fields=[ID_FIELD,
                                       FRENCH_WORD_COL,
                                       ENGLISH_WORD_COL,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL]),
        migrations.CreateModel(name='PartOfSpeech',
                               fields=[ID_FIELD,
                                       FRENCH_WORD_COL,
                                       ENGLISH_WORD_COL,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL,
                                       ('verbType',
                                        models.ForeignKey(null=True, related_name='verbType',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.verbType')),
                                       ('nounType',
                                        models.ForeignKey(null=True, related_name='nounType',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.nounType')),
                                       ]),
        migrations.CreateModel(name='Suffix',
                               fields=[ID_FIELD,
                                       FRENCH_WORD_COL,
                                       ENGLISH_WORD_COL,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL]),
        migrations.CreateModel(name='Prefix',
                               fields=[ID_FIELD,
                                       FRENCH_WORD_COL,
                                       ENGLISH_WORD_COL,
                                       FRENCH_EXPLANATION_COL,
                                       ENGLISH_EXPLANATION_COL]),
        migrations.CreateModel(name='Word',
                               fields=[ID_FIELD,
                                       FRENCH_WORD_COL,
                                       ENGLISH_WORD_COL,
                                       ('ti', models.IntegerField()),
                                       ('otb', models.IntegerField()),
                                       ('definition',
                                        models.ForeignKey(null=True, related_name='definition',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.definition')),
                                       ('etymology',
                                        models.ForeignKey(null=True, related_name='etymology',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.etymology')),
                                       ('prefix',
                                        models.ForeignKey(null=True, related_name='prefix',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.prefix')),
                                       ('suffix',
                                        models.ForeignKey(null=True, related_name='suffix',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.suffix')),
                                       ('partOfSpeech',
                                        models.ForeignKey(null=True, related_name='partOfSpeech',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.partOfSpeech')),
                                       ('etymologicalRoot',
                                        models.ForeignKey(null=True, related_name='etymologicalRoot',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.etymologicalRoot')),
                                       ('semanticCategories',
                                        models.ManyToManyField(to='word_analysis.semanticCategory')),
                                       ]
                               )
    ]
