# Generated by Django 4.2.7 on 2023-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_analysis', '0002_book_line_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_line',
            old_name='text',
            new_name='french',
        ),
        migrations.AddField(
            model_name='book_line',
            name='english',
            field=models.TextField(null=True),
        ),
    ]
