# map of route to title
accordion_route_to_title_data = {
    "route": "route",
    "genre_set_intro": "genre_set_intro",
    "duality": "duality",
    "combination": "combination",
    "repetition": "repetition",
    "opposition": "opposition",
    "intersection": "intersection",
    "parallelism": "parallelism",
    "flat": "flat",
    "two_dimensional": "two_dimensional",
    "constellation": "constellation",
    "curvature": "curvature",
    "numbers": "numbers",
    "addition": "addition",
    "perversion": "perversion",
    "inversion": "inversion",
    "subversion": "subversion",
    "reversion": "reversion",
    "perspectivism": "perspectivism",
    "zero": "zero",
    "one": "one",
    "trois": "trois",
    "three": "three",
    "four": "four",

}
