ALL_REFERENCE_BOOKS = [
    {"author": "Bergson", "title": "Creative Evolution"},
    {"author": "Bergson", "title": "Matter and Memory"},
    {"author": "Bergson", "title": "Time and Free Will"},
    {"author": "de Broglie, Louis", "title": "Ondes et quanta (1923)",
     "link": "https://www.academie-sciences.fr/pdf/dossiers/Broglie/Broglie_pdf/CR1923_p507.pdf"},
    {"author": "Brunschvicg, Léon", "title": "Les étapes de la philosophie mathématique, Paris, Félix Alcan, 1912."},
    {"author": "Blanchot, Maurice", "title": "The Infinite Conversation"},
    {"author": "Deleuze, Gilles", "title": "Difference and Repitition."},
    {"author": "Deleuze, Gilles and Felix Guattari", "title": "A thousand Plateaus."},
    {"author": "Derrida, Jacques", "title": "Violence and Metaphysics"},
    {"author": "Einstein, Albert", "title": "General Relativity"},
    {"author": "Husserl", "title": "Ideas"},
    {"author": "Husserl", "title": "Philosophy of arithmetic"},
    {"author": "Jarry, Alfred", "title": "Gestes et opinions du docteur Faustroll, pataphysicien"},
    {"author": "Lingis, Alphonso", "title": "Preface to Otherwise than Being"},
    {"author": "Llewelyn, John", "title": "Emmanuel Levinas: The Geneaology of Ethics"},
    {"author": "Lyotard, Jean-Francois", "title": "Le Logique de Levinas"},
    {"author": "Peperzak, Adriaan", "title": "To the Other."},
    {"author": "Riemann Bernhard", "title": "Ueber die Hypothesen, welche der Geometrie zu Grunde liegen.",
     "link": "https://www.deutschestextarchiv.de/book/view/riemann_hypothesen_1867?p=7"},
    {"author": "Rolland, Jacques", "title": "L'ethique de Ambiguite"},
    {"author": "Rolland, Jacques", "title": "Introduction to De L'evasion"},
    {"author": "Russell, Bertrand", "title": "An essay on the foundations of geometry"},
    {"author": "Smith, David Eugene", "title": "A History of Modern Mathematics"},
    {"author": "Smith, David Woodruff.", "title": "Husserl"},
    {"author": "Susskind, Leonard", "title": "The Theoretical Minimum"},
    {"author": "Susskind, Leonard", "title": "Quantum Mechanics"},
    {"author": "Susskind, Leonard", "title": "Special Relativity and Classical Field Theory"},
    {"author": "Susskind, Leonard", "title": "General Relaivity"},
    {"author": "Verter, Mitchell", "title": "Levinas, Perverter"},
    {"author": "Verter, Mitchell", "title": "Chronology of Levinas's Metaphorics"},
]
