def all_groups_to_words():
    return ALL_CATEGORIES_TO_WORDS


def all_words_to_categories():
    return ALL_WORDS_TO_CATEGORIES


ALL_CATEGORIES_TO_WORDS = {
    "TENIR": [
        "contente",
        "entrietiens",
        "impatient",
        "detient",
        "appartient",
        "contienne",
        "maintien",
        "obtient",
        "retient",
        "patience",
        "tiendrait",
        "tient",
        "appartenir",
        "contenir",
        "entretenir",
        "maintenir",
        "obtenir",
        "pro-tenir",
        "retenir",
        "soutenir",
        "tenir",
        "contenir",
        "contentement",
        "contenter",
    ],
    "APPEARANCE": {
        "présence",
        "absence",
        "lumière",
        "obscur",
        "vision",
        "vision",
        "visage",
        "face",
        "façade",
        "surface",
        "tergiversation",
        "masque",
    }, "GENESIS": {
        "genesis",
        "origine",
        "mort",
        "résurrection",
        "recurrence",
        "naissance",
        "survivant",
        "surgit",
        "père",
        "mère",
        "fils",
        "frere",
        "sœur",
        "virilite",
        "féminin",
        "maternelle",
        "matière",
        "nourrit",
        "neutre",
        "genre",
        "engendrer",
        "génération",
    },
    "ORALITY": {
        "parler",
        "souffle",
        "rire",
        "baiser",
        "manger",
        "remords",
        "nourrit",
    }, "THEATER": {
        "drame",
        "acte",
        "scene",
        "masque",
        "tragique",
        "travail",
        "œuvre",
        "dechets",
        "absurde",
        "fatal",
        "faire",
        "comique",
        "jouissance",
        "rire",
        "plaisir",
        "MacBeth",
        "Shakespeare",
    }, "MATHÉMATIQUES": {
        "zero",
        "null",
        "une",
        "deuxieme",
        "tiers",
        "unicite",
        "universalite",
        "individualite",
        "dualite",
        "multiplicite",
        "pluralisme",
        "plus",
        "négatif",
        "positif",
        "transitivite",
        "asymétrie",
        "transcendance",
        "infini",
        "Leibniz",
        "intégration",
        "continu",
        "discontinuite",
        "nœud",
        "serie",
        "proximite",
        "prochain",
    }, "GÉOMÉTRIE": {
        "origine",
        "point",
        "intervalle",
        "Descartes",
        "courbure",
        "parallelisme",
        "convexite",
        "concavite",
        "dimension",
        "niveau",
        "hauteur",
        "profondeur",
        "droiture",
    }, "PHYSIQUE": {
        "substance",
        "element",
        "pese",
        "matière",
        "force",
        "gravité",
        "ondes",
    }, "ONTOLOGIE": {
        "ontologie",
        "etre",
        "état",
        "autre",
        "essence",
    }, "EPISTEMOLOGIE": {
        "savoir",
        "doute",
        "scepticisme",
    }, "ETHIQUE": {
        "ethique",
        "bien",
        "bonté",
        "mal",
        "valeur",
        "devrait",
    }, "PLATON": {
        "être",
        "essence",
        "vérité",
        "dialogue",
        "genèse",
        "forme",
        "matière",
    }, "BERGSON": {
        "création",
        "durée",
    }, "HEGEL": {
        "totalité",
        "état",
        "autre",
        "soi",
    }, "HUSSERL": {
        "apparence",
        "passivité",
        "activité",
        "remplissement",
    }, "HEIDEGGER": {
        "ontologie",
        "être",
        "essence",
        "existence",
        "outil",
    }, "DESCARTES": {
        "idée",
        "infini",
        "scepticisme",
    }, "LEIBNIZ": {
        "monade",
        "intégration",
    }, "NIETZSCHE": {
        "rire",
        "au-delà",
        "recurrence",
        "naissance",
        "scepticisme",
        "absurde",
        "sorcières",
        "lascivite",
        "jouir",
        "gratuite",
        "jouissance",
    }}

ALL_WORDS_TO_CATEGORIES = {

}
