ALL_REFERENCE_BOOKS = [
    {"author": "Bergson, Henri", "year": "1889", "title": "Creative Evolution",
     "link": "https://www.gutenberg.org/files/26163/26163-h/26163-h.htm"},
    {"author": "Bergson, Henri", "year": "1896", "title": "Matter and Memory", "link": ""},
    {"author": "Bergson, Henri", "year": "1907", "title": "Time and Free Will",
     "link": "https://www.gutenberg.org/files/56852/56852-h/56852-h.htm"},
    {"author": "de Broglie, Louis", "year": "1923", "title": "Ondes et quanta",
     "link": "https://www.academie-sciences.fr/pdf/dossiers/Broglie/Broglie_pdf/CR1923_p507.pdf"},
    {"author": "Brunschvicg, Léon", "year": "1912", "title": "Les étapes de la philosophie mathématique",
     "publisher": "Paris, Félix Alcan",
     "link": "https://ia800204.us.archive.org/11/items/lestapesdelaph00brun/lestapesdelaph00brun.pdf"},
    {"author": "Blanchot, Maurice", "year": "1969", "title": "The Infinite Conversation", "link": ""},
    {"author": "Ciocan, Cristian and Georges Hansel", "year": "2005", "title": "Levinas Concordance", "link": ""},
    {"author": "Deleuze, Gilles and Felix Guattari", "year": "1980", "title": "A thousand Plateaus", "link": ""},
    {"author": "Deleuze, Gilles", "year": "1968", "title": "Difference and Repetition", "link": ""},
    {"author": "Derrida, Jacques", "year": "1967", "title": "Violence and Metaphysics", "link": ""},
    {"author": "Descartes, René ", "year": "1637", "title": "Geometry",
     "link": "https://www.gutenberg.org/ebooks/26400"},
    {"author": "Einstein, Albert", "year": "1911", "title": "", "link": ""},
    {"author": "Einstein, Albert", "year": "1920", "title": "Relativity: The Special and The General Theory",
     "link": ""},
    {"author": "Husserl", "year": "1891", "title": "Philosophy of arithmetic", "link": ""},
    {"author": "Husserl", "year": "1913", "title": "deas: General Introduction to Pure Phenomenology", "link": ""},
    {"author": "Jarry, Alfred", "year": "1898", "title": "Gestes et opinions du docteur Faustroll, pataphysicien",
     "link": ""},
    {"author": "Lingis, Alphonso", "year": "1974", "title": "Preface to Otherwise than Being", "link": ""},
    {"author": "Llewelyn, John", "year": "1995", "title": "Emmanuel Levinas: The Geneaology of Ethics", "link": ""},
    {"author": "Lyotard, Jean-Francois", "year": "1969", "title": "Le Logique de Levinas", "link": ""},
    {"author": "Peperzak, Adriaan", "year": "1993",
     "title": "To the Other: An Introduction to the Philosophy of Emmanuel Levinas", "link": ""},
    {"author": "Riemann Bernhard", "year": "1854", "title": "On the hypotheses which lie at the foundation of geometry",
     "link": "https://www.emis.de/classics/Riemann/WKCGeom.pdf"},
    {"author": "Rolland, Jacques", "year": "1982", "title": "Introduction pour 'De l'evasion'", "link": ""},
    {"author": "Rolland, Jacques", "year": "1986", "title": "L'ethique de Ambiguite", "link": ""},
    {"author": "Russell, Bertrand", "year": "1897", "title": "An essay on the foundations of geometry", "link": ""},
    {"author": "Smith, David Eugene", "year": "1906", "title": "A History of Modern Mathematics", "link": ""},
    {"author": "Smith, David Eugene", "year": "1922", "title": "Analytic Geometry", "link": ""},
    {"author": "Smith, David Woodruff", "year": "2013", "title": "Husserl", "link": ""},
    {"author": "Susskind, Leonard", "year": "2013", "title": "The Theoretical Minimum", "link": ""},
    {"author": "Susskind, Leonard", "year": "2015", "title": "Quantum Mechanics", "link": ""},
    {"author": "Susskind, Leonard", "year": "2019", "title": "Special Relativity and Classical Field Theory",
     "link": ""},
    {"author": "Susskind, Leonard", "year": "2023", "title": "General Relaivity", "link": ""},
    {"author": "Verter, Mitchell", "title": "Levinas, Perverter", "year": "2007",
     "link": "https://theanarchistlibrary.org/library/mitchell-cowen-verter-levinas-perverter"},
    {"author": "Verter, Mitchell", "year": "2020", "title": "A Chronology of Levinas's Metaphorics",
     "link": "https://karolinum.cz/data/clanek/9828/Interpret_10_1_0142.pdf"},
    {"author": "Verter, Mitchell", "year": "2022", "title": "Levinas and Anarchism",
     "link": "https://waste.org/~roadrunner/writing/Levinas/"},
]
