nav_items = [
    {"route": "summary", "title": "Project Summary"},
    {"route": "mots", "title": "Word list"},
    {"route": "genres", "title": "Genre Sets (GS)"},
    {"route": "relations", "title": "Internal and external relations",
     "subitems": [
         {"route": "duality", "title": "duality"},
         {"route": "repetition", "title": "repetition"},
         {"route": "combination", "title": "combination"},
         {"route": "parallelism", "title": "parallelism"},
         {"route": "opposition", "title": "opposition"},
         {"route": "intersection", "title": "intersection"},
         {"route": "flat", "title": "flat"},
         {"route": "two_dimensional", "title": "two_dimensional"},
         {"route": "constellation", "title": "Constellation"},
     ]},
    {"route": "mathematics", "title": "Mathematics and Physics",
     "subitems": [
         {"route": "curvature", "title": "curvature"},
         {"route": "numbers", "title": "numbers"},
         {"route": "addition", "title": "addition"},
         {"route": "perversion", "title": "perversion"},
         {"route": "inversion", "title": "inversion"},
         {"route": "subversion", "title": "subversion"},
         {"route": "reversion", "title": "reversion"},
         {"route": "perspectivism", "title": "perspectivism"},
         {"route": "zero", "title": "zero"},
         {"route": "one", "title": "one"},
         {"route": "two", "title": "trois"},
         {"route": "three", "title": "three"},
         {"route": "four", "title": "four"},
     ]},
    {"route": "technical", "title": "Technical notes"},
]
