from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(name='SemanticCategory',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID')),
                                       ('french', models.CharField(max_length=100, null=True, unique=True)),
                                       ('english', models.CharField(max_length=100, null=True, unique=True)),
                                       ('french_explanation', models.TextField(null=True)),
                                       ('english_explanation', models.TextField(null=True))]),
        migrations.CreateModel(name='EtymologicalRoot',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID')),
                                       ('root', models.CharField(max_length=100, null=True, unique=True)),
                                       ('french_explanation', models.TextField(null=True)),
                                       ('english_explanation', models.TextField(null=True))
                                       ]),
        migrations.CreateModel(name='VerbType',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID')),
                                       ('french', models.CharField(max_length=100, null=True)),
                                       ('english', models.CharField(max_length=100, null=True)),
                                       ('french_explanation', models.TextField(null=True)),
                                       ('english_explanation', models.TextField(null=True))]),
        migrations.CreateModel(name='NounType',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID')),
                                       ('french', models.CharField(max_length=100, null=True)),
                                       ('english', models.CharField(max_length=100, null=True)),
                                       ('french_explanation', models.TextField(null=True)),
                                       ('english_explanation', models.TextField(null=True))]),
        migrations.CreateModel(name='PartOfSpeech',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID')),
                                       ('french', models.CharField(max_length=100, null=True)),
                                       ('english', models.CharField(max_length=100, null=True)),
                                       ('french_explanation', models.TextField(null=True)),
                                       ('english_explanation', models.TextField(null=True)),
                                       ('verbType',
                                        models.ForeignKey(null=True, related_name='verbType',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.verbType')),
                                       ('nounType',
                                        models.ForeignKey(null=True, related_name='nounType',
                                                          on_delete=models.SET_NULL,
                                                          to='word_analysis.nounType')),
                                       ]),
        migrations.CreateModel(name='Suffix',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID')),
                                       ('french', models.CharField(max_length=100, null=True, unique=True)),
                                       ('english', models.CharField(max_length=100, null=True, unique=True)),
                                       ('french_explanation', models.TextField(null=True)),
                                       ('english_explanation', models.TextField(null=True))]),
        migrations.CreateModel(name='Prefix',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID')),
                                       ('french', models.CharField(max_length=100, null=True, unique=True)),
                                       ('english', models.CharField(max_length=100, null=True, unique=True)),
                                       ('french_explanation', models.TextField(null=True)),
                                       ('english_explanation', models.TextField(null=True))]),
        migrations.CreateModel(name='Word',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                                               verbose_name='ID')),
                                       ('french', models.CharField(max_length=100, unique=True),
                                        ('english', models.CharField(max_length=100, null=True)),
                                        ('french_explanation', models.TextField(null=True)),
                                        ('english_explanation', models.TextField(null=True)),
                                        ('ti', models.IntegerField()),
                                        ('otb', models.IntegerField()),
                                        ('prefix',
                                         models.ForeignKey(null=True, related_name='prefix',
                                                           on_delete=models.SET_NULL,
                                                           to='word_analysis.prefix')),
                                        ('suffix',
                                         models.ForeignKey(null=True, related_name='suffix',
                                                           on_delete=models.SET_NULL,
                                                           to='word_analysis.suffix')),
                                        ('partOfSpeech',
                                         models.ForeignKey(null=True, related_name='partOfSpeech',
                                                           on_delete=models.SET_NULL,
                                                           to='word_analysis.partOfSpeech')),
                                        ('etymologicalRoot',
                                         models.ForeignKey(null=True, related_name='etymologicalRoot',
                                                           on_delete=models.SET_NULL,
                                                           to='word_analysis.etymologicalRoot')),
                                        ('semanticCategories',
                                         models.ManyToManyField(to='word_analysis.semanticCategory')),
                                        ),
                                       ])
    ]
