# Generated by Django 3.1.5 on 2021-01-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(name='SemanticCategory',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField())]),
        migrations.CreateModel(name='EtymologicalRoot',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField())]),
        migrations.CreateModel(name='VerbType',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField())]),
        migrations.CreateModel(name='NounType',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField())]),
        migrations.CreateModel(name='PartOfSpeech',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField()),
                                       ('verbType',
                                        models.ForeignKey(null=True, related_name='verbType',
                                                          to='verbType.id')),
                                       ('nounType',
                                        models.ForeignKey(null=True, related_name='verbType',
                                                          to='verbType.id')),
                                       ]),
        migrations.CreateModel(name='Suffix',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField())]),
        migrations.CreateModel(name='Prefix',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField())]),
        migrations.CreateModel(name='Word',
                               fields=[('id', models.AutoField(auto_created=True, primary_key=True, serialize=True,
                                                               verbose_name='ID'),
                                        'text', models.CharField(max_length=100)),
                                       ('explanation', models.TextField()),
                                       ('prefix',
                                        models.ForeignKey(null=True, related_name='prefix',
                                                          to='prefix.id')),
                                       ('suffix',
                                        models.ForeignKey(null=True, related_name='suffix',
                                                          to='suffix.id')),

                                       ('partOfSpeech',
                                        models.ForeignKey(null=True, related_name='partOfSpeech',
                                                          to='partOfSpeech.id')),

                                       ('etymologicalRoot',
                                        models.ForeignKey(null=True, related_name='etymologicalRoot',
                                                          to='etymologicalRoot.id')),
                                       ('semanticCategories', models.ManyToManyField(to='semanticCategories.id')),

                                       ]),

    ]
